export const QuizActionTypes = {
  CHANGE_STATE: "CHANGE_STATE",
  REODER_QUESTIONS: "REODER_QUESTIONS",
  CHANGE_QUESTION: "CHANGE_QUESTION",
  NEW_GAME: "NEW_GAME",
  CHECK_ANSWER: "CHECK_ANSWER",
}